### ISSUE TITLE
Allowed to add actions when timer is paused

### ISSUE THREAD

**Issue by ethanjaredlee** [iso-athletic/iso-app-web#28]
Not super sure if we want this, but I intended to make it so that if the timer isn't running then we can't add any events.

**Comment by joecummings** [comment]
I agree - would be good to have.

**Comment by abizzaar** [comment]
I think we should let the user add an event when the timer is paused— in the case the players are taking a break and the manager wants to record events that he didn't have time to record during the scrimmage, or forgot to.

**Comment by abizzaar** [comment]
i think we should leave it for now because the managers might forget to track an event during the scrimmage and might wanna add something while the timer is paused?

**Comment by joecummings** [comment]
This NEEDS to be allowed. Just thought of the use case of free throws. Timer should be stopped in that scenario but they need to add actions. As long as the timer doesn't display the starting value then, they should be allowed to add actions.

**Comment by joecummings** [comment]
Closed by @abizzaar
